version: "3.9"

services:
  library:
    container_name: library
    image: library
    restart: always 
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - URL=http://counter:4000/
    build:
        context: ./task
        dockerfile: Dockerfile
        args:
          PORT: 3000
    depends_on:
      counter:
        condition: service_healthy
  
  counter:
    container_name: counter
    image: counter
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      
    build:
        context: ./counter
        dockerfile: Dockerfile
        args:
          PORT: 4000
    healthcheck:
      test: "exit 0"
